extends: "@redhat-cloud-services/eslint-config-redhat-cloud-services"
root: true
globals:
  insights: 'readonly'
  shallow: readonly
  render: 'readonly'
  mount: 'readonly'
  IS_DEV: 'readonly'
rules:
  rulesdir/forbid-pf-relative-imports: 'off'
